---
abstract: 'Module to help locate files using regular expressions.'
author:
  - 'Lloyd Griffiths (lloydg@cpan.org)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: File-RegexMatch
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 1.04
  Cwd: 3.12
  File::Spec: 3.12
  File::stat: 0
  Test::Simple: 0.44
  Tie::IxHash: 1.23
version: v0.1.1
